### ISSUE TITLE
Dark mode is not working as expected

### ISSUE THREAD

**Issue by Titleshwar** [aabhinavg1/FixIt#55]
CompilerSutra dark mode implementation of functionality dark mode need to revisit.

**Comment by aabhinavg1** [comment]
# How to Contribute to Fixing Dark Mode in the FixIt Repository

## Prerequisites
1. **Git**: Ensure Git is installed on your machine. [Download Git](https://git-scm.com/)
2. **Node.js**: Install Node.js to run the project locally. [Download Node.js](https://nodejs.org/)
3. **GitHub Account**: Sign up for a GitHub account if you don’t have one. [Sign up](https://github.com/join)

## Step 1: Fork the Repository
1. Visit the [FixIt Repository](https://github.com/aabhinavg1/FixIt).
2. Click the "Fork" button at the top right of the page. This will create a copy of the repository under your GitHub account.

## Step 2: Clone the Forked Repository
1. After forking, clone your repository locally:
   ```bash
   git clone https://github.com/your-username/FixIt.git
   ```
   Replace `your-username` with your GitHub username.

2. Navigate into the project directory:
   ```bash
   cd FixIt
   ```

## Step 3: Set Up the Project Locally
1. Install project dependencies by running:
   ```bash
   npm install
   ```

2. Run the project locally:
   ```bash
   npm start
   ```

3. Open the project in your browser at `http://localhost:3000` to verify it works.

## Step 4: Debug the Dark Mode Issue
1. The dark mode issue might be due to incorrect CSS or theme variables.
2. Check the following files to investigate:
   - `src/css/custom.css`: Ensure that the dark mode styles are correctly defined.
   - `src/components/HomepageFeatures/styles.module.css`: Verify that this component's styles are not interfering with dark mode.

3. Add necessary code to fix dark mode by adjusting the CSS or JS that controls theme toggling.

For example, verify that your CSS variables are defined for dark mode:
```css
/* Ensure dark mode variables are applied */
[data-theme='dark'] {
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: #21af90;
  --ifm-color-primary-light: #29d5b0;
}
```

Also, check the theme toggling logic to ensure it's functioning properly in `themeContext.js` or a similar file.

## Step 5: Test Your Changes
1. Test your changes locally by switching between light and dark mode.
2. Ensure the dark mode displays as expected across the website.

## Step 6: Commit Your Changes
1. Once the issue is fixed, create a new branch for your changes:
   ```bash
   git checkout -b fix-dark-mode
   ```

2. Add and commit your changes:
   ```bash
   git add .
   git commit -m "Fix dark mode issue"
   ```

## Step 7: Push Changes to Your Fork
1. Push your branch to your fork:
   ```bash
   git push origin fix-dark-mode
   ```

## Step 8: Create a Pull Request
1. Go to your forked repository on GitHub.
2. You will see a prompt to create a pull request. Click "Compare & pull request."
3. Provide a meaningful description of the changes you made.
4. Submit the pull request (PR).

## Step 9: Review and Feedback
1. The repository maintainers will review your PR.
2. Be responsive to any feedback and make necessary changes.

---

By following this guide, beginners can easily get started contributing to the FixIt project and address the dark mode issue.

**Comment by Titleshwar** [comment]
https://github.com/aabhinavg1/FixIt/pull/57 this patch will resolve the issue. Thanks for providing detail explanation how to fix the issue.
